name: Django CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: cd ./todo-app/todo-app
    - run: touch "myfile.txt"
    
